name: Loan Service Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
    - 'loan-service/**'
    - '.github/workflows/loan-service.yml'
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./loan-service
        file: ./loan-service/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: yihwanggeun/loan-service-image:latest
        build-args: |
                    DB_HOST=${{ secrets.DB_HOST }}
                    DB_USER=${{ secrets.DB_USER }}
                    DB_PASSWORD=${{ secrets.DB_PASSWORD }}
                    DB_NAME=${{ secrets.DB_NAME }}